# Generated by Django 5.1 on 2025-02-18 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Boys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('material', models.CharField(choices=[('leather', 'Leather'), ('textiles', 'Textiles'), ('synthetics', 'Synthetics'), ('rubber', 'Rubber'), ('foam', 'Foam'), ('plastic', 'Plastic')], max_length=50)),
                ('brand', models.CharField(choices=[('adidas', 'Adidas'), ('reebok', 'Reebok'), ('woodland', 'Woodland'), ('skechers', 'Skechers'), ('clarks', 'Clarks'), ('crocs', 'Crocs'), ('red_tape', 'Red Tape'), ('sparx', 'Sparx'), ('liberty', 'Liberty'), ('paragon', 'Paragon'), ('bata', 'Bata'), ('mochi', 'Mochi'), ('metro', 'Metro'), ('marc_loire', 'Marc Loire'), ('shoetopia', 'Shoetopia'), ('xe_looks', 'XE Looks'), ('bata_comfit', 'Bata Comfit'), ('trase', 'TRASE'), ('mosac', 'MOSAC')], max_length=50)),
                ('type', models.CharField(choices=[('casual_shoes', 'Casual Shoes'), ('formal_shoes', 'Formal Shoes'), ('party_wear', 'Party Wear'), ('heels', 'Heels'), ('slippers', 'Slippers'), ('flats', 'Flats')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('size', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='6', max_length=20, null=True)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('grey', 'Grey'), ('tan', 'Tan'), ('navy', 'Navy'), ('multicolor', 'Multicolor')], max_length=20)),
                ('category', models.CharField(choices=[('kids', 'Kids'), ('mens', 'Mens'), ('womens', 'Womens')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Anonymous', max_length=50)),
                ('last_name', models.CharField(default='User', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('vendor', 'Vendor'), ('delivery_boy', 'Delivery Boy')], default='customer', max_length=12)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='delivery_boy_profiles/')),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.deliveryboy')),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.user_registration'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('delivery_status', models.CharField(choices=[('Processing', 'Processing'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Processing', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(max_length=10)),
                ('saved_for_later', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('aadhar_card', models.FileField(upload_to='vendor_documents/')),
                ('shop_license', models.FileField(upload_to='vendor_documents/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='vendor_profiles/')),
                ('vendor', models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='user.user_registration')),
            ],
            options={
                'db_table': 'user_vendordetails',
            },
        ),
        # migrations.CreateModel(
        #     name='DeliveryAssignment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('assigned_date', models.DateField(default=django.utils.timezone.now)),
        #         ('delivery_status', models.CharField(default='packed', max_length=50)),
        #         ('is_confirmed', models.BooleanField(default=False)),
        #         ('confirmation_time', models.DateTimeField(blank=True, null=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
        #         ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
        #     ],
        #     options={
        #         'indexes': [models.Index(fields=['order', 'delivery_boy'], name='user_delive_order_i_a26f29_idx')],
        #     },
        # ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='user.user_registration')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
