# Generated by Django 5.1 on 2024-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
