# Generated by Django 5.1 on 2025-02-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_deliveryassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Processing'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
