# Generated by Django 5.1 on 2024-10-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_registration_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='status',
        ),
    ]
