# Generated by Django 5.1 on 2025-02-24 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_deliveryassignment_delivery_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('leather', 'Leather'), ('textiles', 'Textiles'), ('synthetics', 'Synthetics'), ('rubber', 'Rubber'), ('foam', 'Foam'), ('plastic', 'Plastic'), ('Natural rubber', 'Natural Rubber'), ('Heavy-duty rubber', 'Heavy-duty Rubber'), ('Non-marking rubber', 'Non-marking Rubber'), ('TPR', 'TPR'), ('PVC', 'PVC'), ('Nitrile rubber', 'Nitrile Rubber'), ('SBR rubber', 'SBR Rubber'), ('EVA', 'EVA'), ('Polyurethane', 'Polyurethane'), ('Neoprene', 'Neoprene'), ('Vibram', 'Vibram'), ('Cork', 'Cork')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterModelTable(
            name='review',
            table='user_review',
        ),
    ]
