# Generated by Django 5.1 on 2024-10-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_registration_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration'),
        ),
    ]
