# Generated by Django 5.1 on 2025-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_registration_is_active_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('vendor', 'Vendor'), ('delivery_boy', 'Delivery Boy')], default='customer', max_length=12),
        ),
    ]
