# Generated by Django 5.1 on 2025-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_registration_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vendor_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('aadhar_card', models.FileField(upload_to='vendor_documents/')),
                ('shop_license', models.FileField(upload_to='vendor_documents/')),
                ('shop_photos', models.ManyToManyField(blank=True, to='user.shopphoto')),
            ],
        ),
    ]
