# Generated by Django 5.1 on 2024-10-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_registration_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
