# Generated by Django 5.1 on 2025-01-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_registration_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('aadhar_card', models.FileField(upload_to='vendor_documents/')),
                ('shop_license', models.FileField(upload_to='vendor_documents/')),
                ('vendor', models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='user.user_registration')),
            ],
            options={
                'db_table': 'user_vendordetails',
            },
        ),
    ]
