# Generated by Django 5.1 on 2025-01-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_registration_is_active_vendordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profiles/'),
        ),
    ]
