# Generated by Django 5.1 on 2025-01-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_shopphoto_vendordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='user.user_registration'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
