# Generated by Django 5.1 on 2024-10-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_registration_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='username',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='last_name',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
