# Generated by Django 5.1 on 2025-01-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
