# Generated by Django 5.1 on 2025-01-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_product_brand_alter_product_color_and_more'),
    ]

    operations = [
    ]
