# Generated by Django 5.1 on 2025-01-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_clean_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('reebok', 'Reebok'), ('woodland', 'Woodland'), ('skechers', 'Skechers'), ('clarks', 'Clarks'), ('crocs', 'Crocs'), ('red_tape', 'Red Tape'), ('sparx', 'Sparx'), ('liberty', 'Liberty'), ('paragon', 'Paragon'), ('bata', 'Bata'), ('mochi', 'Mochi'), ('metro', 'Metro'), ('marc_loire', 'Marc Loire'), ('shoetopia', 'Shoetopia'), ('xe_looks', 'XE Looks'), ('bata_comfit', 'Bata Comfit'), ('trase', 'TRASE'), ('mosac', 'MOSAC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('grey', 'Grey'), ('tan', 'Tan'), ('navy', 'Navy'), ('multicolor', 'Multicolor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('leather', 'Leather'), ('textiles', 'Textiles'), ('synthetics', 'Synthetics'), ('rubber', 'Rubber'), ('foam', 'Foam'), ('plastic', 'Plastic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('casual_shoes', 'Casual Shoes'), ('formal_shoes', 'Formal Shoes'), ('party_wear', 'Party Wear'), ('heels', 'Heels'), ('slippers', 'Slippers'), ('flats', 'Flats')], max_length=50),
        ),
    ]
