# Generated by Django 5.1 on 2025-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_product_brand_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
