# Generated by Django 5.1 on 2024-10-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_review_email_review_name_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='default_value', max_length=50),
            preserve_default=False,
        ),
    ]
