# Generated by Django 5.1 on 2024-10-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(default='default_value', max_length=1000),
            preserve_default=False,
        ),
    ]
