# Generated by Django 5.1 on 2025-02-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_registration_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='phone_number',
        ),
    ]
