# Generated by Django 5.1 on 2024-10-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
