# Generated by Django 5.1 on 2025-02-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_deliveryboyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
