# Generated by Django 5.1 on 2025-02-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_deliveryboyprofile_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboyprofile',
            name='state',
        ),
    ]
