# Generated by Django 5.1 on 2025-02-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userprofile_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
    ]
