# Generated by Django 5.1 on 2025-02-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_userprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
