# Generated by Django 5.1 on 2025-02-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
